name: flutter_ddd
description: "Flutter DDD"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  mobx_codegen: ^2.7.0
  dio: ^5.8.0+1
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4

dependency_overrides: # Workaround for MobX incompatibility with freezed 3.0.0
  source_gen: ">=1.2.1 <3.0.0"

flutter:
  generate: true
  uses-material-design: true
