@startuml CurrencyModel
class CurrencyModel {
  + String symbol
  + double priceChange
  + double priceChangePercent
  + double weightedAvgPrice
  + double prevClosePrice
  + double lastPrice
  + double lastQty
  + double bidPrice 
  + double bidQty
  + double askPrice
  + double askQty
  + double openPrice
  + double highPrice
  + double lowPrice
  + double volume
  + double quoteVolume
  + double openTime
  + double closeTime
  + double firstId
  + double lastId
  + double count
  
  + static List<CurrencyModel> fromList(List<Map<String, dynamic>> list)
  + factory fromJson(Map<String, dynamic> map)
}
@enduml
