@startuml CurrenciesModel
class CurrenciesModel {
  + String symbol
  + String price
  + static List<CurrenciesModel> fromList(List<Map<String, dynamic>> list)
  + factory fromJson(Map<String, dynamic> map)
  + Map<String, dynamic> toJson()
}
@enduml
